# Generated by Django 4.2.6 on 2023-10-19 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_expenseshared_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseshared',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
